#!/bin/bash

version=$(cat VERSION| tr -d '\n')

mkdir -p bin/macosx/
mkdir -p bin/linux/

echo "Building OS X version"
GOOS=darwin GOARCH=amd64 go build ./civo.go
mv civo bin/macosx/

echo "Building Linux version"
GOOS=linux GOARCH=amd64 go build ./civo.go
mv civo bin/linux/

cd bin
zip -r civo-v$version.zip INSTALL.md linux macosx

git tag v$version
git push --tags
open https://github.com/absolutedevops/civo/releases/new?tag=v$version
open bin/
